receivers:
  otlp:
    protocols:
      grpc:
      http:
  zipkin:
    endpoint: "0.0.0.0:9411"

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, zipkin]
      processors: [batch]
      exporters: [otlp/jaeger]
